from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()

client = OpenAI()

def chat(input: str):
    """
    Interacts with the OpenAI GPT-3.5 model to generate a response to a given input string.

    This function sends a message to the OpenAI GPT-3.5 chat model and retrieves its response. 
    The function uses the OpenAI API, configured with environment variables for API access. 
    It assumes the role of an assistant in the conversation context.

    Parameters:
    - input (str): The input message to which the GPT-3.5 model will respond.

    Returns:
    - str: The response generated by the GPT-3.5 model based on the input message.

    Note:
    - The function requires the OpenAI API key to be set in the environment variables.
    - The 'gpt-3.5-turbo' model is used in this implementation. 
    """
    response = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "assistant", "content": input }
        ]
    )
    return response['choices'][0]['message']['content']